export const GET_PROPERTIES_REQUEST = 'GET_PROPERTIES_REQUEST'
export const GET_PROPERTIES_SUCCESS = 'GET_PROPERTIES_SUCCESS'
export const GET_PROPERTIES_FAILURE = 'GET_PROPERTIES_FAILURE'

export const GET_PROPERTY_SUMMARY_REQUEST = 'GET_PROPERTY_SUMMARY_REQUEST'
export const GET_PROPERTY_SUMMARY_SUCCESS = 'GET_PROPERTY_SUMMARY_SUCCESS'
export const GET_PROPERTY_SUMMARY_FAILURE = 'GET_PROPERTY_SUMMARY_FAILURE'

export const SAVE_PROPERTY_REQUEST = 'SAVE_PROPERTY_REQUEST'
export const SAVE_PROPERTY_SUCCESS = 'SAVE_PROPERTY_SUCCESS'
export const SAVE_PROPERTY_FAILURE = 'SAVE_PROPERTY_FAILURE'

export const DELETE_PROPERTIES_REQUEST = 'DELETE_PROPERTIES_REQUEST'
export const DELETE_PROPERTIES_SUCCESS = 'DELETE_PROPERTIES_SUCCESS'
export const DELETE_PROPERTIES_FAILURE = 'DELETE_PROPERTIES_FAILURE'
